version: '3'

services:

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

  redis:
    container_name: redis_container
    image: redis
    volumes:
      - redis:/data
    ports:
      - "6379:6379"

  prometheus:
    container_name: prometheus_container
    image: prom/prometheus
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    ports:
      - "9090:9090"

  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - "3000:3000"

  elasticsearch:
    image: elasticsearch:8.6.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      xpack.security.enabled: "false"
    volumes:
      - elastic:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.6.2
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch

  logstash:
    image: logstash:8.6.2
    volumes:
      - ./.logstash:/usr/share/logstash/pipeline
      - ./logs:/var/log/todo
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch

volumes:
  postgres:
  redis:
  prometheus:
  grafana:
  elastic: